# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Cobly’s Blogß
tagline:          The Maker
url:              http://ctrefethen.github.io
paginate:         1
baseurl:          /
author:
  name:           Colby Trefethen
#  url:            https://twitter.com/mdo
#  email:          colby@colbytrefethen.com

# Custom vars
version:          1.0.0
#github:
#  repo:           https://github.com/poole/poole
